# Generated by Django 5.1.6 on 2025-07-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'daily_order', 'scheduled_time', 'id']},
        ),
        migrations.AddField(
            model_name='event',
            name='daily_order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of this event within the day', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled time for this event', null=True),
        ),
    ]
