# Generated by Django 5.1.6 on 2025-07-28 14:42

import workorders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_alter_event_options_event_daily_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('text', 'Text')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='job_attachments/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='jobattachment',
            name='file',
            field=models.FileField(upload_to=workorders.models.job_attachment_upload_path, validators=[workorders.models.validate_file_type, workorders.models.validate_file_size]),
        ),
    ]
