# Generated by Django 5.1.6 on 2025-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_jobattachment_file_size_jobattachment_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False, help_text='Mark if this specific event was completed'),
        ),
        migrations.AddField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this event was marked complete', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='completed_by',
            field=models.CharField(blank=True, help_text='Who marked this event complete', max_length=100),
        ),
    ]
