# Generated by Django 5.1.6 on 2025-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Not in QuickBooks'), ('in_quickbooks', 'In QuickBooks'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
